# Exclude files and directories from pre-commit checks (addition to the default excludes)
exclude: |
  (?x)(
    src/generated/.*
    | src/third_party/.*
  )
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-json
