# Exclude files and directories from pre-commit checks (addition to the default excludes)
exclude: |
  (?x)(
    src/generated/.*
    | src/third_party/.*
  )
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-json
        exclude: ^(\.devcontainer|\.vscode)

  # TODO(update-this): Update below hooks to met your project's needs
  - repo: local
    hooks:
      - id: ruff-check
        name: ruff check
        language: system
        types_or: [python, pyi]
        entry: uv run ruff check
        args: [--fix]

      - id: ruff-format
        name: ruff format
        language: system
        types_or: [python, pyi]
        entry: uv run ruff format

      - id: ty
        name: ty
        language: system
        types_or: [python, pyi]
        entry: uv run ty check

      - id: pytest
        name: pytest
        language: system
        pass_filenames: false
        entry: uv run pytest -m unit
