# TODO(bootstrap): If project does not use Docker Compose for dependent services such as database or cache, delete this file

# You can add `.env` file and define environment variables there
# to override the default values below.

# TODO(bootstrap): If project need to set up services such as database, cache, message broker, etc., add it as service
services:
  postgres:
    image: postgres:18-alpine@sha256:d3e1620b530c944afa6e887d22eb899824da68e19c52024bf98f5220c88a65b2
    ports:
      - ${POSTGRES_HOST:-127.0.0.1}:${POSTGRES_PORT:-5432}:5432
    environment:
      POSTGRES_DB: db
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    volumes:
      - postgres-data:/var/lib/postgresql/18/docker

volumes:
  postgres-data:
