# You can add `.env` file and define environment variables there
# to override the default values below.

# TODO(bootstrap): Update this file to meet your project's needs
services:
  postgres:
    image: postgres:18.4-trixie@sha256:8ff36f3c66371cba71d20ceedccfc3de9669a68737607888c4ef0af93abe8e39
    ports:
      - ${POSTGRES_HOST:-127.0.0.1}:${POSTGRES_PORT:-5432}:5432
    environment:
      POSTGRES_DB: db
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    volumes:
      - postgres-data:/var/lib/postgresql/18/docker

volumes:
  postgres-data:
