# TODO(bootstrap): If project does not use Docker Compose for dependent services such as database or cache, delete this file

# You can add `.env` file and define environment variables there
# to override the default values below.

# TODO(bootstrap): If project need to set up services such as database, cache, message broker, etc., add it as service
services:
  postgres:
    image: postgres:18.4-trixie@sha256:29ee7bb30d804447dc9a91fd0d74322ae1dc3a4072cc6346f70a5ed6e783b565
    ports:
      - ${POSTGRES_HOST:-127.0.0.1}:${POSTGRES_PORT:-5432}:5432
    environment:
      POSTGRES_DB: db
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    volumes:
      - postgres-data:/var/lib/postgresql/18/docker

volumes:
  postgres-data:
